version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build: ./
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ../env_enroute
    expose:
      - 8000